# House Price Prediction: Advanced Regression Techniques- Data Wrangling

In [240]:
#Import necessary modules

import requests
import pandas as pd
import opendatasets as od
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [241]:
#Using the kaggle api to download the dataset

od.download('https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data?select=train.csv')

Skipping, found downloaded files in ".\house-prices-advanced-regression-techniques" (use force=True to force download)

In [242]:
# Load train.csv into a DataFrame
train_df = pd.read_csv("train.csv")

# Load test.csv into a DataFrame
test_df = pd.read_csv("test.csv")

Now we have the dataframes made for the training and testing datasets and will take a look at the data

In [243]:
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [244]:
train_df.shape

(1460, 81)

In [245]:
test_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [246]:
train_df.shape

(1460, 81)

In [247]:
#New dataframe with the combined datasets in order to view all of the data

full_df = pd.concat([train_df, test_df], ignore_index=True)
full_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [248]:
full_df.shape

(2919, 81)

In [249]:
full_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [250]:
full_df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice        float64
Length: 81, dtype: object

In [251]:
full_df.set_index("Id", inplace=True)

In [252]:
full_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [253]:
full_df.info

<bound method DataFrame.info of       MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id
1             60       RL         65.0     8450   Pave   NaN      Reg
2             20       RL         80.0     9600   Pave   NaN      Reg
3             60       RL         68.0    11250   Pave   NaN      IR1
4             70       RL         60.0     9550   Pave   NaN      IR1
5             60       RL         84.0    14260   Pave   NaN      IR1
...          ...      ...          ...      ...    ...   ...      ...
2915         160       RM         21.0     1936   Pave   NaN      Reg
2916         160       RM         21.0     1894   Pave   NaN      Reg
2917          20       RL        160.0    20000   Pave   NaN      Reg
2918          85       RL         62.0    10441   Pave   NaN      Reg
2919          60       RL         74.0     9627   Pave   NaN      Reg

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
Id                                    ...
1            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN
2            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN
3            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN
4            Lvl    AllPub    Corner  ...        0    NaN    NaN         NaN
5            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN
...          ...       ...       ...  ...      ...    ...    ...         ...
2915         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN
2916         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN
2917         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN
2918         Lvl    AllPub    Inside  ...        0    NaN  MnPrv        Shed
2919         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice
Id
1          0      2    2008        WD         Normal   208500.0
2          0      5    2007        WD         Normal   181500.0
3          0      9    2008        WD         Normal   223500.0
4          0      2    2006        WD        Abnorml   140000.0
5          0     12    2008        WD         Normal   250000.0
...      ...    ...     ...       ...            ...        ...
2915       0      6    2006        WD         Normal        NaN
2916       0      4    2006        WD        Abnorml        NaN
2917       0      9    2006        WD        Abnorml        NaN
2918     700      7    2006        WD         Normal        NaN
2919       0     11    2006        WD         Normal        NaN

[2919 rows x 80 columns]>

In [254]:
#Print out the first row transposed for sample home submission

full_df.iloc[0].T

MSSubClass             60
MSZoning               RL
LotFrontage          65.0
LotArea              8450
Street               Pave
                   ...
MoSold                  2
YrSold               2008
SaleType               WD
SaleCondition      Normal
SalePrice        208500.0
Name: 1, Length: 80, dtype: object

In [255]:
#Count the number of missing values in each column and then sort. Count column shows us the number of instances that are
# missing and the % will show the percent of each column missing

missing = pd.concat([full_df.isnull().sum(), 100 * full_df.isnull().mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending=False)

              count          %
PoolQC         2909  99.657417
MiscFeature    2814  96.402878
Alley          2721  93.216855
Fence          2348  80.438506
SalePrice      1459  49.982871
...             ...        ...
1stFlrSF          0   0.000000
2ndFlrSF          0   0.000000
LowQualFinSF      0   0.000000
GrLivArea         0   0.000000
CentralAir        0   0.000000

[80 rows x 2 columns]

In [256]:
#Pool quality has the most missing values. We will check what the unique missing values are and the counts of each.

poolqc_counts = full_df['PoolQC'].value_counts()
print(poolqc_counts)

Ex    4
Gd    4
Fa    2
Name: PoolQC, dtype: int64

In [257]:
#Drop the pool quality column with very little information to help us

full_df = full_df.drop('PoolQC', axis=1)

In [258]:
full_df.shape

(2919, 79)

In [259]:
misc_feature_counts = full_df['MiscFeature'].value_counts()
print(misc_feature_counts)

Shed    95
Gar2     5
Othr     4
TenC     1
Name: MiscFeature, dtype: int64

In [260]:
# Create a new column 'HasShed' indicating the presence of a shed as most non missing values of misc feature are shed

full_df['HasShed'] = full_df['MiscFeature'].apply(lambda x: 1 if x == 'Shed' else 0)

In [261]:
#Drop the misc feature column for the new has shed column

full_df = full_df.drop('MiscFeature', axis=1)
full_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,HasShed
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,0,2,2008,WD,Normal,208500.0,0
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,0,5,2007,WD,Normal,181500.0,0
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,0,9,2008,WD,Normal,223500.0,0
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,0,2,2006,WD,Abnorml,140000.0,0
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,0,12,2008,WD,Normal,250000.0,0

In [262]:
#Alley column unlikely to provide significant insights into our predictions with over 90% missing values

full_df = full_df.drop('Alley', axis=1)
full_df.shape

(2919, 78)

In [263]:
full_df.select_dtypes(object)

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,Fence,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,Typ,NaN,Attchd,RFn,TA,TA,Y,NaN,WD,Normal
2,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,...,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,WD,Normal
4,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,...,Typ,Gd,Detchd,Unf,TA,TA,Y,NaN,WD,Abnorml
5,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,...,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,RM,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,...,Typ,NaN,NaN,NaN,NaN,NaN,Y,NaN,WD,Normal
2916,RM,Pave,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,Norm,Norm,...,Typ,NaN,CarPort,Unf,TA,TA,Y,NaN,WD,Abnorml
2917,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,...,Typ,TA,Detchd,Unf,TA,TA,Y,NaN,WD,Abnorml
2918,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,...,Typ,NaN,NaN,NaN,NaN,NaN,Y,MnPrv,WD,Normal
2919,RL,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,Norm,...,Typ,TA,Attchd,Fin,TA,TA,Y,NaN,WD,Normal

In [264]:
#Checking for unique values in utilities as there is no variation seen. Drop column since only 1 value not AllPub

utility_count = full_df['Utilities'].value_counts()
print(utility_count)
full_df = full_df.drop('Utilities', axis=1)
full_df.shape

AllPub    2916
NoSeWa       1
Name: Utilities, dtype: int64

(2919, 77)

In [265]:
#Loop through the columns of type object and show the unique counts of each

for column in full_df.columns:
    if full_df[column].dtype == 'object':
        unique_counts = full_df[column].value_counts()
        print(f"Column: {column}")
        print(unique_counts)

Column: MSZoning
RL         2265
RM          460
FV          139
RH           26
C (all)      25
Name: MSZoning, dtype: int64
Column: Street
Pave    2907
Grvl      12
Name: Street, dtype: int64
Column: LotShape
Reg    1859
IR1     968
IR2      76
IR3      16
Name: LotShape, dtype: int64
Column: LandContour
Lvl    2622
HLS     120
Bnk     117
Low      60
Name: LandContour, dtype: int64
Column: LotConfig
Inside     2133
Corner      511
CulDSac     176
FR2          85
FR3          14
Name: LotConfig, dtype: int64
Column: LandSlope
Gtl    2778
Mod     125
Sev      16
Name: LandSlope, dtype: int64
Column: Neighborhood
NAmes      443
CollgCr    267
OldTown    239
Edwards    194
Somerst    182
NridgHt    166
Gilbert    165
Sawyer     151
NWAmes     131
SawyerW    125
Mitchel    114
BrkSide    108
Crawfor    103
IDOTRR      93
Timber      72
NoRidge     71
StoneBr     51
SWISU       48
ClearCr     44
MeadowV     37
BrDale      30
Blmngtn     28
Veenker     24
NPkVill     23
Blueste     10
Name: Neighborhood, dtype: int64
Column: Condition1
Norm      2511
Feedr      164
Artery      92
RRAn        50
PosN        39
RRAe        28
PosA        20
RRNn         9
RRNe         6
Name: Condition1, dtype: int64
Column: Condition2
Norm      2889
Feedr       13
Artery       5
PosN         4
PosA         4
RRNn         2
RRAn         1
RRAe         1
Name: Condition2, dtype: int64
Column: BldgType
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: BldgType, dtype: int64
Column: HouseStyle
1Story    1471
2Story     872
1.5Fin     314
SLvl       128
SFoyer      83
2.5Unf      24
1.5Unf      19
2.5Fin       8
Name: HouseStyle, dtype: int64
Column: RoofStyle
Gable      2310
Hip         551
Gambrel      22
Flat         20
Mansard      11
Shed          5
Name: RoofStyle, dtype: int64
Column: RoofMatl
CompShg    2876
Tar&Grv      23
WdShake       9
WdShngl       7
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: RoofMatl, dtype: int64
Column: Exterior1st
VinylSd    1025
MetalSd     450
HdBoard     442
Wd Sdng     411
Plywood     221
CemntBd     126
BrkFace      87
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
Stone         2
CBlock        2
ImStucc       1
Name: Exterior1st, dtype: int64
Column: Exterior2nd
VinylSd    1014
MetalSd     447
HdBoard     406
Wd Sdng     391
Plywood     270
CmentBd     126
Wd Shng      81
BrkFace      47
Stucco       47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
Other         1
Name: Exterior2nd, dtype: int64
Column: MasVnrType
None       1742
BrkFace     879
Stone       249
BrkCmn       25
Name: MasVnrType, dtype: int64
Column: ExterQual
TA    1798
Gd     979
Ex     107
Fa      35
Name: ExterQual, dtype: int64
Column: ExterCond
TA    2538
Gd     299
Fa      67
Ex      12
Po       3
Name: ExterCond, dtype: int64
Column: Foundation
PConc     1308
CBlock    1235
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: Foundation, dtype: int64
Column: BsmtQual
TA    1283
Gd    1209
Ex     258
Fa      88
Name: BsmtQual, dtype: int64
Column: BsmtCond
TA    2606
Gd     122
Fa     104
Po       5
Name: BsmtCond, dtype: int64
Column: BsmtExposure
No    1904
Av     418
Gd     276
Mn     239
Name: BsmtExposure, dtype: int64
Column: BsmtFinType1
Unf    851
GLQ    849
ALQ    429
Rec    288
BLQ    269
LwQ    154
Name: BsmtFinType1, dtype: int64
Column: BsmtFinType2
Unf    2493
Rec     105
LwQ      87
BLQ      68
ALQ      52
GLQ      34
Name: BsmtFinType2, dtype: int64
Column: Heating
GasA     2874
GasW       27
Grav        9
Wall        6
OthW        2
Floor       1
Name: Heating, dtype: int64
Column: HeatingQC
Ex    1493
TA     857
Gd     474
Fa      92
Po       3
Name: HeatingQC, dtype: int64
Column: CentralAir
Y    2723
N     196
Name: CentralAir, dtype: int64
Column: Electrical
SBrkr    2671
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: Electrical, dtype: int64
Column: KitchenQual
TA    1492
Gd    1151
Ex     205
Fa      70
Name: KitchenQual, dtype: int64
Column: Functional
Typ     2717
Min2      70
Min1      65
Mod       35
Maj1      19
Maj2       9
Sev        2
Name: Functional, dtype: int64
Column: FireplaceQu
Gd    744
TA    592
Fa     74
Po     46
Ex     43
Name: FireplaceQu, dtype: int64
Column: GarageType
Attchd     1723
Detchd      779
BuiltIn     186
Basment      36
2Types       23
CarPort      15
Name: GarageType, dtype: int64
Column: GarageFinish
Unf    1230
RFn     811
Fin     719
Name: GarageFinish, dtype: int64
Column: GarageQual
TA    2604
Fa     124
Gd      24
Po       5
Ex       3
Name: GarageQual, dtype: int64
Column: GarageCond
TA    2654
Fa      74
Gd      15
Po      14
Ex       3
Name: GarageCond, dtype: int64
Column: PavedDrive
Y    2641
N     216
P      62
Name: PavedDrive, dtype: int64
Column: Fence
MnPrv    329
GdPrv    118
GdWo     112
MnWw      12
Name: Fence, dtype: int64
Column: SaleType
WD       2525
New       239
COD        87
ConLD      26
CWD        12
ConLI       9
ConLw       8
Oth         7
Con         5
Name: SaleType, dtype: int64
Column: SaleCondition
Normal     2402
Partial     245
Abnorml     190
Family       46
Alloca       24
AdjLand      12
Name: SaleCondition, dtype: int64

In [266]:
#Drop columns with very low variability with not much information to provide

columns_to_drop = ['Street', 'RoofMatl', 'Heating', 'Condition2']
full_df.drop(columns_to_drop, axis=1, inplace=True)
full_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,...,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,HasShed
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Reg,Lvl,Inside,Gtl,CollgCr,Norm,...,0,0,NaN,0,2,2008,WD,Normal,208500.0,0
2,20,RL,80.0,9600,Reg,Lvl,FR2,Gtl,Veenker,Feedr,...,0,0,NaN,0,5,2007,WD,Normal,181500.0,0
3,60,RL,68.0,11250,IR1,Lvl,Inside,Gtl,CollgCr,Norm,...,0,0,NaN,0,9,2008,WD,Normal,223500.0,0
4,70,RL,60.0,9550,IR1,Lvl,Corner,Gtl,Crawfor,Norm,...,0,0,NaN,0,2,2006,WD,Abnorml,140000.0,0
5,60,RL,84.0,14260,IR1,Lvl,FR2,Gtl,NoRidge,Norm,...,0,0,NaN,0,12,2008,WD,Normal,250000.0,0

In [270]:
# Define the columns to encode
columns_to_encode = ['ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'HeatingQC', 'KitchenQual', 'FireplaceQu', 'GarageQual', 'GarageCond']

# Create a copy of the DataFrame to avoid modifying the original data
encoded_df = full_df.copy()

# Iterate over the columns and perform imputation and encoding
for column in columns_to_encode:
    # Create a new category 'NA' to handle missing values
    categories = ['Po', 'Fa', 'TA', 'Gd', 'Ex', 'NA']
    
    # Impute missing values with 'NA'
    imputer = SimpleImputer(strategy='constant', fill_value='NA')
    encoded_df[column] = imputer.fit_transform(encoded_df[[column]])
    
    # Perform ordinal encoding
    ordinal_encoder = OrdinalEncoder(categories=[categories])
    encoded_df[column] = ordinal_encoder.fit_transform(encoded_df[[column]])

In [ ]:
['BsmtExposure','BsmtFinType1', 'BsmtFinType2', 'Functional', 'LandSlope']

In [271]:
#Check if the types of the columns switched from object to int

for column_name in columns_to_encode:
    column_type = full_df[column_name].dtypes
    print(f"Column '{column_name}': {column_type}")

Column 'ExterQual': object
Column 'ExterCond': object
Column 'BsmtQual': object
Column 'BsmtCond': object
Column 'HeatingQC': object
Column 'KitchenQual': object
Column 'FireplaceQu': object
Column 'GarageQual': object
Column 'GarageCond': object

In [269]:
poolqc_counts = full_df['ExterCond'].value_counts()
print(poolqc_counts)

TA    2538
Gd     299
Fa      67
Ex      12
Po       3
Name: ExterCond, dtype: int64

In [111]:
full_df.select_dtypes(object)

,MSZoning,LotShape,LandContour,LotConfig,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,Exterior1st,...,MasVnrType,Foundation,CentralAir,Electrical,GarageType,GarageFinish,PavedDrive,Fence,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,RL,Reg,Lvl,Inside,CollgCr,Norm,1Fam,2Story,Gable,VinylSd,...,BrkFace,PConc,Y,SBrkr,Attchd,RFn,Y,NaN,WD,Normal
2,RL,Reg,Lvl,FR2,Veenker,Feedr,1Fam,1Story,Gable,MetalSd,...,None,CBlock,Y,SBrkr,Attchd,RFn,Y,NaN,WD,Normal
3,RL,IR1,Lvl,Inside,CollgCr,Norm,1Fam,2Story,Gable,VinylSd,...,BrkFace,PConc,Y,SBrkr,Attchd,RFn,Y,NaN,WD,Normal
4,RL,IR1,Lvl,Corner,Crawfor,Norm,1Fam,2Story,Gable,Wd Sdng,...,None,BrkTil,Y,SBrkr,Detchd,Unf,Y,NaN,WD,Abnorml
5,RL,IR1,Lvl,FR2,NoRidge,Norm,1Fam,2Story,Gable,VinylSd,...,BrkFace,PConc,Y,SBrkr,Attchd,RFn,Y,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,RM,Reg,Lvl,Inside,MeadowV,Norm,Twnhs,2Story,Gable,CemntBd,...,None,CBlock,Y,SBrkr,NaN,NaN,Y,NaN,WD,Normal
2916,RM,Reg,Lvl,Inside,MeadowV,Norm,TwnhsE,2Story,Gable,CemntBd,...,None,CBlock,Y,SBrkr,CarPort,Unf,Y,NaN,WD,Abnorml
2917,RL,Reg,Lvl,Inside,Mitchel,Norm,1Fam,1Story,Gable,VinylSd,...,None,CBlock,Y,SBrkr,Detchd,Unf,Y,NaN,WD,Abnorml
2918,RL,Reg,Lvl,Inside,Mitchel,Norm,1Fam,SFoyer,Gable,HdBoard,...,None,PConc,Y,SBrkr,NaN,NaN,Y,MnPrv,WD,Normal
2919,RL,Reg,Lvl,Inside,Mitchel,Norm,1Fam,2Story,Gable,HdBoard,...,BrkFace,PConc,Y,SBrkr,Attchd,Fin,Y,NaN,WD,Normal

In [114]:
# Filter the dataset for normal sale conditions
filtered_df = full_df[full_df['SaleCondition'] == 'Normal']

# Remove the SaleCondition column
filtered_df = filtered_df.drop('SaleCondition', axis=1)

In [115]:
# Calculate mean and median sales prices for full_df
mean_sales_price_full = full_df['SalePrice'].mean()
median_sales_price_full = full_df['SalePrice'].median()

# Calculate mean and median sales prices for filtered_df
mean_sales_price_filtered = filtered_df['SalePrice'].mean()
median_sales_price_filtered = filtered_df['SalePrice'].median()

# Print the results
print("Mean sales price - Full dataset:", mean_sales_price_full)
print("Median sales price - Full dataset:", median_sales_price_full)
print("Mean sales price - Filtered dataset:", mean_sales_price_filtered)
print("Median sales price - Filtered dataset:", median_sales_price_filtered)

Mean sales price - Full dataset: 180921.19589041095
Median sales price - Full dataset: 163000.0
Mean sales price - Filtered dataset: 175202.21953255427
Median sales price - Filtered dataset: 160000.0